name: pandera-dev
channels:
  - conda-forge

dependencies:
  # environment management
  - pip

  # pandera dependencies
  - packaging >= 20.0
  - hypothesis >= 5.41.1
  - numpy >= 1.19.0
  - pandas >= 1.2.0
  - scipy
  - wrapt
  - pyyaml >=5.1
  - typing_inspect >= 0.6.0
  - typing_extensions >= 3.7.4.3
  - frictionless
  - pyarrow
  - pydantic

  # mypy extra
  - pandas-stubs <= 1.4.3.220807
  - pyspark-stubs

  # pyspark extra
  - pyspark >= 3.2.0

  # modin extra
  - modin
  - protobuf <= 3.20.3

  # dask extra
  - dask
  - distributed

  # geopandas extra
  - geopandas
  - shapely

  # fastapi extra
  - fastapi

  # testing and dependencies
  - black >= 22.1.0

  # testing
  - isort >= 5.7.0
  - codecov
  - mypy <= 0.971
  - pylint = 2.12.2
  - pytest
  - pytest-cov
  - pytest-xdist
  - pytest-asyncio
  - xdoctest
  - nox
  - importlib_metadata # required if python < 3.8

  # fastapi testing
  - uvicorn
  - python-multipart

  # documentation
  - sphinx
  - sphinx-panels
  - sphinx-autodoc-typehints <= 1.14.1
  - sphinx-copybutton
  - recommonmark

  # packaging
  - twine

  # performance testing
  - asv

  # optional
  - pre_commit

  - pip:
      - furo
      - ray <= 1.7.0; python_version < '3.10'
      - types-click
      - types-pyyaml
      - types-pkg_resources
      - types-requests
      - jupyterlite_sphinx
